CREATE TABLE IF NOT EXISTS photos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filename TEXT NOT NULL,
    upload_date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS current_photo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filename TEXT NOT NULL
);
